### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by skoxo** [mpratt/google-photos-upload#1]
From the documentation it is not clear to me how to run the actual code itself. I tried running the `google-photos-upload` command from several folders in the extracted zip file and from within Python CLI, using both python2.7 and python3, but it returns 'command not found'.

When I go to the 'google_photos_upload' folder and run `python cli.py`, it returns: 'ImportError: attempted relative import with no known parent package'

I've successfully installed the dependencies using the `pip install -e` command, so that's not the issue.

Could you please give me some directions as I'd love to try your code!

**Comment by mpratt** [comment]
Hi @skoxo !
Do you have ~/.local/bin in your $PATH ?
